// AUTO-GENERATED by scripts/push-figma-tokens.mjs from DESIGN.md.
// Paste this entire file into a Figma Plugin-API runner (e.g. use_figma) and run.
// After running, re-export the file's variables and overwrite .figma/figma-state.json.
// Collection: "CSS Wrangler / Tokens"

const colls = await figma.variables.getLocalVariableCollectionsAsync();
let coll = colls.find(c => c.name === "CSS Wrangler / Tokens");
if (!coll) {
  coll = figma.variables.createVariableCollection("CSS Wrangler / Tokens");
  coll.renameMode(coll.modes[0].modeId, "Dark");
  coll.addMode("Light");
}
const dark = coll.modes.find(m => m.name === "Dark");
const light = coll.modes.find(m => m.name === "Light");
if (!dark) throw new Error('Mode "Dark" missing from collection');
if (!light) throw new Error('Mode "Light" missing from collection');

const allIds = coll.variableIds;
const all = await Promise.all(allIds.map(id => figma.variables.getVariableByIdAsync(id)));
const byName = new Map(all.map(v => [v.name, v]));

const log = { created: [], updated: [], skipped: [] };

return log;